//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("stockModel", "FK_Item_0_0", "Equipment", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gestion_du_stock.Equipment), "Item", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gestion_du_stock.Item), true)]
[assembly: EdmRelationshipAttribute("stockModel", "FK_ItemIntervention_0_0", "Intervention", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gestion_du_stock.Intervention), "ItemIntervention", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gestion_du_stock.ItemIntervention), true)]
[assembly: EdmRelationshipAttribute("stockModel", "FK_ItemIntervention_1_0", "Item", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gestion_du_stock.Item), "ItemIntervention", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gestion_du_stock.ItemIntervention), true)]

#endregion

namespace Gestion_du_stock
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class stockEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet stockEntities à l'aide de la chaîne de connexion trouvée dans la section 'stockEntities' du fichier de configuration d'application.
        /// </summary>
        public stockEntities() : base("name=stockEntities", "stockEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet stockEntities.
        /// </summary>
        public stockEntities(string connectionString) : base(connectionString, "stockEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet stockEntities.
        /// </summary>
        public stockEntities(EntityConnection connection) : base(connection, "stockEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Account> Accounts
        {
            get
            {
                if ((_Accounts == null))
                {
                    _Accounts = base.CreateObjectSet<Account>("Accounts");
                }
                return _Accounts;
            }
        }
        private ObjectSet<Account> _Accounts;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Equipment> Equipments
        {
            get
            {
                if ((_Equipments == null))
                {
                    _Equipments = base.CreateObjectSet<Equipment>("Equipments");
                }
                return _Equipments;
            }
        }
        private ObjectSet<Equipment> _Equipments;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Intervention> Interventions
        {
            get
            {
                if ((_Interventions == null))
                {
                    _Interventions = base.CreateObjectSet<Intervention>("Interventions");
                }
                return _Interventions;
            }
        }
        private ObjectSet<Intervention> _Interventions;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Item> Items
        {
            get
            {
                if ((_Items == null))
                {
                    _Items = base.CreateObjectSet<Item>("Items");
                }
                return _Items;
            }
        }
        private ObjectSet<Item> _Items;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<ItemIntervention> ItemInterventions
        {
            get
            {
                if ((_ItemInterventions == null))
                {
                    _ItemInterventions = base.CreateObjectSet<ItemIntervention>("ItemInterventions");
                }
                return _ItemInterventions;
            }
        }
        private ObjectSet<ItemIntervention> _ItemInterventions;

        #endregion
        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Accounts. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToAccounts(Account account)
        {
            base.AddObject("Accounts", account);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Equipments. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToEquipments(Equipment equipment)
        {
            base.AddObject("Equipments", equipment);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Interventions. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToInterventions(Intervention intervention)
        {
            base.AddObject("Interventions", intervention);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Items. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToItems(Item item)
        {
            base.AddObject("Items", item);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet ItemInterventions. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToItemInterventions(ItemIntervention itemIntervention)
        {
            base.AddObject("ItemInterventions", itemIntervention);
        }

        #endregion
    }
    

    #endregion
    
    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="stockModel", Name="Account")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Account : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Account.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="login">Valeur initiale de la propriété login.</param>
        /// <param name="password">Valeur initiale de la propriété password.</param>
        /// <param name="locked">Valeur initiale de la propriété locked.</param>
        /// <param name="can_edit_stock">Valeur initiale de la propriété can_edit_stock.</param>
        /// <param name="can_edit_account">Valeur initiale de la propriété can_edit_account.</param>
        public static Account CreateAccount(global::System.Int64 id, global::System.String login, global::System.String password, global::System.Int64 locked, global::System.Int64 can_edit_stock, global::System.Int64 can_edit_account)
        {
            Account account = new Account();
            account.id = id;
            account.login = login;
            account.password = password;
            account.locked = locked;
            account.can_edit_stock = can_edit_stock;
            account.can_edit_account = can_edit_account;
            return account;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String login
        {
            get
            {
                return _login;
            }
            set
            {
                OnloginChanging(value);
                ReportPropertyChanging("login");
                _login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("login");
                OnloginChanged();
            }
        }
        private global::System.String _login;
        partial void OnloginChanging(global::System.String value);
        partial void OnloginChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 locked
        {
            get
            {
                return _locked;
            }
            set
            {
                OnlockedChanging(value);
                ReportPropertyChanging("locked");
                _locked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("locked");
                OnlockedChanged();
            }
        }
        private global::System.Int64 _locked;
        partial void OnlockedChanging(global::System.Int64 value);
        partial void OnlockedChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 can_edit_stock
        {
            get
            {
                return _can_edit_stock;
            }
            set
            {
                Oncan_edit_stockChanging(value);
                ReportPropertyChanging("can_edit_stock");
                _can_edit_stock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("can_edit_stock");
                Oncan_edit_stockChanged();
            }
        }
        private global::System.Int64 _can_edit_stock;
        partial void Oncan_edit_stockChanging(global::System.Int64 value);
        partial void Oncan_edit_stockChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 can_edit_account
        {
            get
            {
                return _can_edit_account;
            }
            set
            {
                Oncan_edit_accountChanging(value);
                ReportPropertyChanging("can_edit_account");
                _can_edit_account = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("can_edit_account");
                Oncan_edit_accountChanged();
            }
        }
        private global::System.Int64 _can_edit_account;
        partial void Oncan_edit_accountChanging(global::System.Int64 value);
        partial void Oncan_edit_accountChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="stockModel", Name="Equipment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Equipment : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Equipment.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="name">Valeur initiale de la propriété name.</param>
        public static Equipment CreateEquipment(global::System.Int64 id, global::System.String name)
        {
            Equipment equipment = new Equipment();
            equipment.id = id;
            equipment.name = name;
            return equipment;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> maxUses
        {
            get
            {
                return _maxUses;
            }
            set
            {
                OnmaxUsesChanging(value);
                ReportPropertyChanging("maxUses");
                _maxUses = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("maxUses");
                OnmaxUsesChanged();
            }
        }
        private Nullable<global::System.Int64> _maxUses;
        partial void OnmaxUsesChanging(Nullable<global::System.Int64> value);
        partial void OnmaxUsesChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("stockModel", "FK_Item_0_0", "Item")]
        public EntityCollection<Item> Items
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Item>("stockModel.FK_Item_0_0", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Item>("stockModel.FK_Item_0_0", "Item", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="stockModel", Name="Intervention")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Intervention : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Intervention.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="name">Valeur initiale de la propriété name.</param>
        /// <param name="checkingState">Valeur initiale de la propriété checkingState.</param>
        public static Intervention CreateIntervention(global::System.Int64 id, global::System.String name, global::System.Int64 checkingState)
        {
            Intervention intervention = new Intervention();
            intervention.id = id;
            intervention.name = name;
            intervention.checkingState = checkingState;
            return intervention;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String startedDate
        {
            get
            {
                return _startedDate;
            }
            set
            {
                OnstartedDateChanging(value);
                ReportPropertyChanging("startedDate");
                _startedDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("startedDate");
                OnstartedDateChanged();
            }
        }
        private global::System.String _startedDate;
        partial void OnstartedDateChanging(global::System.String value);
        partial void OnstartedDateChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String endedDate
        {
            get
            {
                return _endedDate;
            }
            set
            {
                OnendedDateChanging(value);
                ReportPropertyChanging("endedDate");
                _endedDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("endedDate");
                OnendedDateChanged();
            }
        }
        private global::System.String _endedDate;
        partial void OnendedDateChanging(global::System.String value);
        partial void OnendedDateChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 checkingState
        {
            get
            {
                return _checkingState;
            }
            set
            {
                OncheckingStateChanging(value);
                ReportPropertyChanging("checkingState");
                _checkingState = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("checkingState");
                OncheckingStateChanged();
            }
        }
        private global::System.Int64 _checkingState;
        partial void OncheckingStateChanging(global::System.Int64 value);
        partial void OncheckingStateChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("stockModel", "FK_ItemIntervention_0_0", "ItemIntervention")]
        public EntityCollection<ItemIntervention> ItemInterventions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemIntervention>("stockModel.FK_ItemIntervention_0_0", "ItemIntervention");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemIntervention>("stockModel.FK_ItemIntervention_0_0", "ItemIntervention", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="stockModel", Name="Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Item : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Item.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="buyingDate">Valeur initiale de la propriété buyingDate.</param>
        /// <param name="barCode">Valeur initiale de la propriété barCode.</param>
        /// <param name="state">Valeur initiale de la propriété state.</param>
        /// <param name="idEquipment">Valeur initiale de la propriété idEquipment.</param>
        public static Item CreateItem(global::System.Int64 id, global::System.String buyingDate, global::System.Int64 barCode, global::System.Int64 state, global::System.Int64 idEquipment)
        {
            Item item = new Item();
            item.id = id;
            item.buyingDate = buyingDate;
            item.barCode = barCode;
            item.state = state;
            item.idEquipment = idEquipment;
            return item;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String serialNumber
        {
            get
            {
                return _serialNumber;
            }
            set
            {
                OnserialNumberChanging(value);
                ReportPropertyChanging("serialNumber");
                _serialNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("serialNumber");
                OnserialNumberChanged();
            }
        }
        private global::System.String _serialNumber;
        partial void OnserialNumberChanging(global::System.String value);
        partial void OnserialNumberChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String expiryDate
        {
            get
            {
                return _expiryDate;
            }
            set
            {
                OnexpiryDateChanging(value);
                ReportPropertyChanging("expiryDate");
                _expiryDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("expiryDate");
                OnexpiryDateChanged();
            }
        }
        private global::System.String _expiryDate;
        partial void OnexpiryDateChanging(global::System.String value);
        partial void OnexpiryDateChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String buyingDate
        {
            get
            {
                return _buyingDate;
            }
            set
            {
                OnbuyingDateChanging(value);
                ReportPropertyChanging("buyingDate");
                _buyingDate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("buyingDate");
                OnbuyingDateChanged();
            }
        }
        private global::System.String _buyingDate;
        partial void OnbuyingDateChanging(global::System.String value);
        partial void OnbuyingDateChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 barCode
        {
            get
            {
                return _barCode;
            }
            set
            {
                OnbarCodeChanging(value);
                ReportPropertyChanging("barCode");
                _barCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("barCode");
                OnbarCodeChanged();
            }
        }
        private global::System.Int64 _barCode;
        partial void OnbarCodeChanging(global::System.Int64 value);
        partial void OnbarCodeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private global::System.Int64 _state;
        partial void OnstateChanging(global::System.Int64 value);
        partial void OnstateChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idEquipment
        {
            get
            {
                return _idEquipment;
            }
            set
            {
                OnidEquipmentChanging(value);
                ReportPropertyChanging("idEquipment");
                _idEquipment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idEquipment");
                OnidEquipmentChanged();
            }
        }
        private global::System.Int64 _idEquipment;
        partial void OnidEquipmentChanging(global::System.Int64 value);
        partial void OnidEquipmentChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("stockModel", "FK_Item_0_0", "Equipment")]
        public Equipment Equipment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipment>("stockModel.FK_Item_0_0", "Equipment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipment>("stockModel.FK_Item_0_0", "Equipment").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Equipment> EquipmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipment>("stockModel.FK_Item_0_0", "Equipment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Equipment>("stockModel.FK_Item_0_0", "Equipment", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("stockModel", "FK_ItemIntervention_1_0", "ItemIntervention")]
        public EntityCollection<ItemIntervention> ItemInterventions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemIntervention>("stockModel.FK_ItemIntervention_1_0", "ItemIntervention");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemIntervention>("stockModel.FK_ItemIntervention_1_0", "ItemIntervention", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="stockModel", Name="ItemIntervention")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemIntervention : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet ItemIntervention.
        /// </summary>
        /// <param name="idItem">Valeur initiale de la propriété idItem.</param>
        /// <param name="idIntervention">Valeur initiale de la propriété idIntervention.</param>
        public static ItemIntervention CreateItemIntervention(global::System.Int64 idItem, global::System.Int64 idIntervention)
        {
            ItemIntervention itemIntervention = new ItemIntervention();
            itemIntervention.idItem = idItem;
            itemIntervention.idIntervention = idIntervention;
            return itemIntervention;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> used
        {
            get
            {
                return _used;
            }
            set
            {
                OnusedChanging(value);
                ReportPropertyChanging("used");
                _used = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("used");
                OnusedChanged();
            }
        }
        private Nullable<global::System.Int64> _used;
        partial void OnusedChanging(Nullable<global::System.Int64> value);
        partial void OnusedChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idItem
        {
            get
            {
                return _idItem;
            }
            set
            {
                if (_idItem != value)
                {
                    OnidItemChanging(value);
                    ReportPropertyChanging("idItem");
                    _idItem = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idItem");
                    OnidItemChanged();
                }
            }
        }
        private global::System.Int64 _idItem;
        partial void OnidItemChanging(global::System.Int64 value);
        partial void OnidItemChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idIntervention
        {
            get
            {
                return _idIntervention;
            }
            set
            {
                if (_idIntervention != value)
                {
                    OnidInterventionChanging(value);
                    ReportPropertyChanging("idIntervention");
                    _idIntervention = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idIntervention");
                    OnidInterventionChanged();
                }
            }
        }
        private global::System.Int64 _idIntervention;
        partial void OnidInterventionChanging(global::System.Int64 value);
        partial void OnidInterventionChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("stockModel", "FK_ItemIntervention_0_0", "Intervention")]
        public Intervention Intervention
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Intervention>("stockModel.FK_ItemIntervention_0_0", "Intervention").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Intervention>("stockModel.FK_ItemIntervention_0_0", "Intervention").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Intervention> InterventionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Intervention>("stockModel.FK_ItemIntervention_0_0", "Intervention");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Intervention>("stockModel.FK_ItemIntervention_0_0", "Intervention", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("stockModel", "FK_ItemIntervention_1_0", "Item")]
        public Item Item
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("stockModel.FK_ItemIntervention_1_0", "Item").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("stockModel.FK_ItemIntervention_1_0", "Item").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Item> ItemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("stockModel.FK_ItemIntervention_1_0", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Item>("stockModel.FK_ItemIntervention_1_0", "Item", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
